### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by FQZhang** [sebastiansulinski/ssd-form#1]
Is there any way I can use my own regex?

For example,  with Password validation, it has to match /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/;
But if I would like to change the length criteria to 8 or more, how Do I do that?

Another example, phone number, I would like to validate the format of phone number for certain country with regex, etc

**Comment by sebastiansulinski** [comment]
You can use `extendValidationRules` property to create your own validation rules - even though `password` rule already exists, if you add new `password` validation rule, it will overwrite the original one.
Here's an example:

```javascript
$('form[data-ajax-form]').ssdForm({

    extendValidationRules: {

        password: function(element) {

            var pattern = /(?=.\d)(?=.[a-z])(?=.*[A-Z]).{6,}/;
            return pattern.test(element.value) && element.value.length >= 8;
        }

    }

});
```

```html
<input
    type="password"
    name="password"
    id="password"
    data-validate="required|password"
    placeholder="Provide your password"
>
```

**Comment by FQZhang** [comment]
Thank you for your quick response.

My case is that I generate regex from PHP code. So that is dynamic, it's better to have a way I could pass regex to ssd-form plugin, rather than creating a fixed rule each time.

**Comment by sebastiansulinski** [comment]
I that case it would probably be better if you could echo the regex somewhere within the body of the page - using some hidden element, then fetch it using jquery and use within the script - alternatively you could make an ajax call which would return regex back.
It's not something I would recommend, but it is an option.
It would depend on whether it is per view / page load or whether you'd have all of the regex rules that you can fetch in one request using ajax. If so, you could add a property and two methods to the `extendValidationRules` object - property would store all regexes and methods would fetch the whole list and the other would get you the regex for a given index - something along these lines:

```javascript
$('form[data-ajax-form]').ssdForm({

  extendValidationRules: {
	
		rules: {},
	
		getRule: function(index) {
	
			if ($.isEmptyObject(this.rules)) {
				this.fetchRules();
			}
	
			return this.rules[index];
	
		},
	
		fetchRules: function() {
	
			var self = this;
			
			$.getJSON('/path/to-rules', function(data) {
				self.rules = data;
			});
		
		},
		
		password: function(element) {
		
			return (
				this.getRule('password').test(element.value) && 
				element.value.length >= 8
			);
			
		}
		
	}

});
```
I didn't test it, but it should give you an idea.

**Comment by FQZhang** [comment]
I just add regex function to the code, it takes data-rule as regex in HTML, and validate again regex.

**Comment by sebastiansulinski** [comment]
I've just added `regex` rule - please check latest version `1.4.0`
