### ISSUE TITLE
Regular express conflict with condition separator

### ISSUE THREAD

**Issue by FQZhang** [sebastiansulinski/ssd-form#3]
with `regex` rules, if it contains `|`, element.rules will consider it as validation separator.

For example
```javascript
regex:^\({0,1}((0|\+61)(2|4|3|7|8)){0,1}\){0,1}(\ |-){0,1}[0-9]{2}(\ |-){0,1}[0-9]{2}(\ |-){0,1}[0-9]{1}(\ |-){0,1}[0-9]{3}$;
```
It validates australia phone number.

the `|` will be treated as the same pipe sign in `data-validate="requried|min:3"`

is it a good idea to make `||` as a separator for data-validate?

**Comment by sebastiansulinski** [comment]
Not really - this would break backward compatibility and i believe with the time you would find another issue with it. My suggestion would be to do what you did originally, and move it to a separate attribute on the given input something like `data-regex` or something along these lines.

**Comment by FQZhang** [comment]
I added data-regex to hold regex value in a pull request.

Example:

```html
<label>
	<span data-validation="whatever_field_needs_to_be_validated">
		<span data-case="regex">Some error message</span>
	</span>
</label>
<input type="text" data-validate="required|regex" data-regex="^[0-9]*$">
```
