### ISSUE TITLE
How to: Validate Radio Button

### ISSUE THREAD

**Issue by FQZhang** [sebastiansulinski/ssd-form#5]
is there any way to validate radio button group?
for example:

<input type="radio" name="a" value="1">
<input type="radio" name="a" value="2">
<input type="radio" name="a" value="3">

how do I validate if one of them is checked

**Comment by sebastiansulinski** [comment]
At present there isn't a validation rule that would validate radio button group, but I'll have a think about it and try to add it to the next release.

**Comment by FQZhang** [comment]
I added radio button validation functon called "selected" and make a pull request #7 

HTML:
```html
<label for="radio_button">
    Please select radio button
    <span data-validation="radio_button">
        <span data-case="selected">Please select any radio button</span>
    </span>
</label>
<input type="radio" name="radio_button" value="1" data-validate="selected" required="required">
<input type="radio" name="radio_button" value="2">
<input type="radio" name="radio_button" value="3">
<input type="radio" name="radio_button" value="4">
```

**Comment by sebastiansulinski** [comment]
Validation for the `radio` button group has been added in `v1.5.2`
